{% set name = "uvicorn-worker" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uvicorn_worker-{{ version }}.tar.gz
  sha256: 6baeab7b2162ea6b9612cbe149aa670a76090ad65a267ce8e27316ed13c7de7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - uvicorn-standard >=0.14.0
    # gunicorn is not available for windows
    - gunicorn >=20.1.0

test:
  imports:
    - uvicorn_worker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kludex/uvicorn-worker
  summary: Uvicorn worker for Gunicorn!
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
