{% set name = "uvicorn-worker" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uvicorn_worker-{{ version }}.tar.gz
  sha256: f6894544391796be6eeed37d48cae9d7739e5a105f7e37061eccef2eac5a0295

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - uvicorn-standard >=0.14.0
# gunicorn is not available for windows
    - gunicorn >=20.1.0

test:
  imports:
    - uvicorn_worker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kludex/uvicorn-worker
  summary: Uvicorn worker for Gunicorn!
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
